// apps/native-daemon/src/inference/grammar.rs

/// GBNF (GPT-BNF) grammar for enforcing strict JSON output matching DpdpAuditReport.
///
/// ## SOTA Optimizations:
/// 1. O(1) Stack Depth: Uses EBNF `*` to prevent C++ stack overflows on long arrays.
/// 2. Strict Bounds: `dpdp_trust_score` physically constrained to 0-100.
/// 3. Canonical Strings: High-performance regex-style string evaluation.
/// 4. Robust Whitespace: Tolerates `\r\n` and PRE-COMMA array spaces to prevent aborts.
/// 5. AI Escape Hatches: Explicitly allows "UNKNOWN" variants to prevent forced hallucinations.

pub const DPDP_AUDIT_GRAMMAR: &str = r#"
root ::= object

object ::= 
    "{" ws 
    "\"global_legal_reasoning\"" ws ":" ws string ws "," ws
    "\"violations\"" ws ":" ws violation-array ws "," ws
    "\"dpdp_trust_score\"" ws ":" ws trust-score ws 
    "}"

# 🚀 SOTA FIX 1: Added `ws` BEFORE the comma `(violation ws ("," ...)` 
# This prevents sampler aborts if the LLM generates a newline before the comma.
violation-array ::= "[" ws (violation ws ("," ws violation ws)*)? "]"

violation ::= 
    "{" ws
    "\"statute_reference\"" ws ":" ws string ws "," ws
    "\"violation_type\"" ws ":" ws violation-type ws "," ws
    "\"evidence_quote\"" ws ":" ws string ws "," ws
    "\"network_action\"" ws ":" ws network-action ws "," ws
    "\"offending_entities\"" ws ":" ws string-array ws
    "}"

violation-type ::= 
    "\"PURPOSE_LIMITATION_VIOLATION\"" |
    "\"CONSENT_NOT_FREE_OR_SPECIFIC\"" |
    "\"NOTICE_INADEQUATE\"" |
    "\"DATA_RETENTION_LIMIT_EXCEEDED\"" |
    "\"CHILD_CONSENT_VIOLATION\"" |
    "\"SECURITY_SAFEGUARDS_MISSING\"" |
    "\"GRIEVANCE_REDRESSAL_INADEQUATE\"" |
    "\"BREACH_NOTIFICATION_FAILURE\"" |
    "\"SDF_OBLIGATIONS_MISSING\"" |
    "\"CROSS_BORDER_TRANSFER_VIOLATION\"" |
    "\"UNKNOWN_VIOLATION\""  # 🚀 SOTA FIX 2: The AI Escape Hatch

network-action ::= 
    "\"BLOCK_THIRD_PARTY\"" |
    "\"STRIP_TELEMETRY_HEADER\"" |
    "\"SPOOF_HARDWARE_API\"" |
    "\"INJECT_GPC_SIGNAL\"" |
    "\"WARN_USER_ONLY\"" |
    "\"UNKNOWN_ACTION\""     # 🚀 SOTA FIX 2: The AI Escape Hatch

# 🚀 SOTA FIX 1: Applied pre-comma whitespace tolerance here as well
string-array ::= "[" ws (string ws ("," ws string ws)*)? "]"

# Canonical JSON string definition. Handles all escapes natively.
string ::= "\"" ( [^"\\\x00-\x1F] | "\\" ( ["\\/bfnrt] | "u" [0-9a-fA-F] [0-9a-fA-F] [0-9a-fA-F] [0-9a-fA-F] ) )* "\""

# Physically constrained to 0-100.
trust-score ::= "0" | [1-9] [0-9]? | "100"

# Supports Windows-style line endings (\r) generated by LLMs
ws ::= [ \t\r\n]*
"#;

pub fn validate_grammar(grammar: &str) -> Result<(), GrammarValidationError> {
    if grammar.is_empty() {
        return Err(GrammarValidationError::EmptyGrammar);
    }
    
    let required_rules = [
        "root ::=",
        "object ::=",
        "violation-array ::=",
        "violation ::=",
        "violation-type ::=",
        "network-action ::=",
        "string-array ::=",
        "string ::=",
        "trust-score ::=",
    ];

    for rule in required_rules {
        if !grammar.contains(rule) {
            return Err(GrammarValidationError::MissingRule(rule.to_string()));
        }
    }
    
    Ok(())
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GrammarValidationError {
    EmptyGrammar,
    MissingRule(String),
}

impl std::fmt::Display for GrammarValidationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::EmptyGrammar => write!(f, "Grammar string is empty"),
            Self::MissingRule(rule) => write!(f, "Grammar missing required rule: {}", rule),
        }
    }
}

impl std::error::Error for GrammarValidationError {}